[package]
name = "enigma"
description = "Create and modify Certificate Signing Requests"
version = "0.1.0"
edition = "2024"
readme = "README.md"
repository = "https://github.com/ekiuts/enigma"
license = "The Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
colored = "2.0.4"
dirs = "6.0.0"
users = "0.11.0"
